spring:
  profiles:
    active: develop-h2
    group:
      develop-h2:
        - common
        - develop
      develop-mysql:
        - common
        - develop
      production:
        - common
---
spring:
  config:
    activate:
      on-profile: common
---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        DEBUG
    com:
      junyounggoat:
        dreamstore:
          userservice:
            DEBUG

---
spring:
  config:
    activate:
      on-profile: develop-h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
  flyway:
    locations: classpath:/db/migration/h2
---
spring:
  config:
    activate:
      on-profile: develop-mysql
  datasource:
    url: ${spring-datasource-url}
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}
  flyway:
    locations: classpath:/db/migration/mysql_develop
---
spring:
  config:
    activate:
      on-profile: production
  h2:
    console:
      enabled: false
  datasource:
    url: ${spring-datasource-url}
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}
  flyway:
    locations: classpath:/db/migration/mysql_production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
