spring:
  profiles:
    include: repository
    active: develop-h2
    group:
      develop-h2:
        - common
        - develop
      develop-mysql:
        - common
        - develop
      production:
        - common
---
spring:
  config:
    activate:
      on-profile: develop

logging:
  level:
    org:
      springframework:
        DEBUG
    com:
      junyounggoat:
        dreamstore:
          userservice:
            DEBUG
