spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: develop-h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
  flyway:
    locations: classpath:/db/migration/h2
---
spring:
  config:
    activate:
      on-profile: develop-mysql
  datasource:
    url: ${spring-datasource-url}
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}
  flyway:
    locations: classpath:/db/migration/mysql_develop
---
spring:
  config:
    activate:
      on-profile: production
  h2:
    console:
      enabled: false
  datasource:
    url: ${spring-datasource-url}
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}
  flyway:
    locations: classpath:/db/migration/mysql_production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${spring-redis-host}
      port: ${spring-redis-port}
      timeout: 3000
